### ISSUE TITLE
Unable to Read File from Different Directory

### ISSUE THREAD

**Issue by agnesnatasya** [nus-cs2103-AY1920S2/forum#17]
Hi I am doing the IP3 project. For Level 7, I read input from duke.txt and I use a relative path, relative from the root of the project folder. I use ""./data/duke.txt" path (I am using MacOS), because the duke.txt is located inside data folder. When I run the Duke.java (inside src/main/java), it works without any error.

However, when I do the runtest.sh as part of the Automated UI testing, they give some errors saying that they cannot find the file. 

Also, when I tried to run the JAR file that I created, they complain that they cannot find this file. 

Is this because when I run the runtest.sh or the JAR file, the location is different from the Duke.java? But should not be a problem right because it is relative to the root of the project?

Any help will be appreciated, thank you!

**Comment by okkhoy** [comment]
Can you post your actual output, including the directories? I suspect you get this issue because of the paths involved.

**Comment by mario7lorenzo** [comment]
Hi! For the first qn, I suspect that your shell script is located differently as your duke class, so the relative path is not the same. And the same applies to the JAR file in my opinion.

Relative path is very risky

**Comment by agnesnatasya** [comment]
My root project directory is duke.

The duke.txt, data to be loaded is inside duke/data/duke.txt, that is why my file path is "./data/duke.txt"

The UI testing files (runtest.sh, input.txt, Actual.txt, expected.txt) is in duke/text-ui-files.

When I run Duke.java (located inside "src/main/java/duke/Duke.java") using IntelliJ, redirecting input from input.txt and redirecting it to actual.txt, it works fine, there is no error. 

The JAR file is inside duke/out/artifacts/duke-jar2/duke.jar. When I run it, it gives "File for loading not found", a statement that I print when I cannot find the file.

I ran the sh runtest.sh, the output (after removing the JUnit test files) is similar
```
Exception in thread "main" java.lang.NullPointerException
	at TaskList.add(TaskList.java:31)
	at Duke.addTask(Duke.java:109)
	at Duke.processInput(Duke.java:85)
	at Duke.run(Duke.java:39)
	at Duke.main(Duke.java:34)
< 	File for loading not found
5a5,28
>    ____________________________________________________________
> 	Got it. I've added this task:
> 		[D][✘] return book (by: Dec 2 2019 06:00 PM)
> 	Now you have 1 tasks in the list.
>    ____________________________________________________________
>    ____________________________________________________________
> 	Got it. I've added this task:
> 		[E][✘] project meeting(at: Dec 2 2019 06:00 PM)
> 	Now you have 2 tasks in the list.
>    ____________________________________________________________
>    ____________________________________________________________
> 	Got it. I've added this task:
> 		[T][✘] borrow book
> 	Now you have 3 tasks in the list.
>    ____________________________________________________________
>    ____________________________________________________________
> 	Here are the tasks in your list:
> 	1.[D][✘] return book (by: Dec 2 2019 06:00 PM)
> 	2.[E][✘] project meeting(at: Dec 2 2019 06:00 PM)
> 	3.[T][✘] borrow book
>    ____________________________________________________________
>    ____________________________________________________________
> 	Bye. Hope to see you again soon!
>    ____________________________________________________________
Test result: FAILED
```


Thank you!

**Comment by mario7lorenzo** [comment]
I've tried in my system. You need to place the tasks.txt at the proper position. What I mean by that is, if you run the JAR file, you need to place the tasks.txt inside the path relative to the `.jar` file. If you run the shell script, you need to place the tasks.txt inside the path relative to the root.
