### ISSUE TITLE
Errors when running JAR file for peer review

### ISSUE THREAD

**Issue by raniceyue** [nus-cs2103-AY1920S2/forum#70]
I am currently using Ubuntu 19.10 eoan. 

I am trying to run a JAR file from the command line for peer review, using the command `java -jar [filename].jar`. 

For the first person I was supposed to review, everything ran smoothly. However, for the second person, I obtained the following error and the GUI failed to launch. 

```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I was just wondering, is this an issue with the Java installation on my system, or is it just an issue with the JAR file?

**Comment by okkhoy** [comment]
I suspect this is because the developer did not bundle the JavaFX dependency for all platforms.

**Comment by junhaotan** [comment]
I tried running the JAR file from command line, but ran into this error.

```
Error: LinkageError occurred while loading main class Launcher
java.lang.UnsupportedClassVersionError: Launcher has been compiled 
by a more recent version of the Java Runtime (class file version 56.0), 
this version of the Java Runtime only recognizes class file versions up to 55.0
```

Checking online, I found out that JRE 56 is compatible with Java SE 12 instead of 11 which we are using. Do I have to install Java 12 so that I can run the JAR file?

**Comment by okkhoy** [comment]
@junhaotan no need.
You can state the observation as NA  in the evaluation survey and write the reason.
Second: you can create a bug report on the developer's repository indicating the problem.

**Comment by junhaotan** [comment]
Noted. Thanks prof @okkhoy!
